---
# defaults file for node-exporter
# https://github.com/prometheus/node_exporter/releases/tag/v1.8.2
# https://github.com/prometheus/node_exporter/releases/download/v1.8.2/node_exporter-1.8.2.linux-arm64.tar.gz
package: 'Node Exporter'
node_exporter_version: 1.8.2
architecture: arm64
operating_system: linux
install_tmp_path: '/tmp'
install_bin_path: '/usr/local/bin'
install_cfg_path: '/usr/local/etc'
