---
# tasks file for ubuntu_desktop

- name: 'Install alactritty terminal'
  ansible.builtin.package:
    name: alacritty
    state: present

# https://galaxy.ansible.com/ui/repo/published/community/general/?version=11.4.4
- name: 'Install `btop` snap'
  community.general.snap:
    name: btop
    state: present

- name: 'Install `rpi-imager` snap'
  community.general.snap:
    name: rpi-imager
    state: present

- name: 'Install `tmux` snap'
  community.general.snap:
    name: tmux
    classic: true
    state: present

